set_property PACKAGE_PIN Y17 [get_ports RxD_PC]
set_property PACKAGE_PIN W17 [get_ports TxD_PC]
#set_property PACKAGE_PIN U17 [get_ports RxD_PC]
#set_property PACKAGE_PIN U18 [get_ports TxD_PC]
#set_property PACKAGE_PIN P1 [get_ports RxD_Tail]
#set_property PACKAGE_PIN N1 [get_ports TxD_Tail]
set_property PACKAGE_PIN U17 [get_ports RxD_Tail]
set_property PACKAGE_PIN U18 [get_ports TxD_Tail]
set_property PACKAGE_PIN AA15 [get_ports RxD_HW]
set_property PACKAGE_PIN AA14 [get_ports TxD_HW]
set_property PACKAGE_PIN R2 [get_ports RxD_Tracker]
set_property PACKAGE_PIN R3 [get_ports TxD_Tracker]
set_property PACKAGE_PIN Y12 [get_ports TxD_KJG]
set_property PACKAGE_PIN Y13 [get_ports RxD_KJG]
set_property PACKAGE_PIN AB12 [get_ports RxD_ServoA]
set_property PACKAGE_PIN AA12 [get_ports TxD_ServoA]
set_property PACKAGE_PIN AB14 [get_ports RxD_ServoB]
set_property PACKAGE_PIN AB13 [get_ports TxD_ServoB]



set_property IOSTANDARD LVCMOS33 [get_ports RxD_PC]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_PC]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_HW]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_HW]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_KJG]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_KJG]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_Tail]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_Tail]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_Tracker]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_Tracker]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_ServoA]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_ServoA]
set_property IOSTANDARD LVCMOS33 [get_ports RxD_ServoB]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_ServoB]